#pragma once
#define PI 3.14159265359

LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK TemporalWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK FreqWndProc(HWND, UINT, WPARAM, LPARAM);

int createChildWindows(HWND parentHandle);